apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-app-project
  namespace: argocd
spec:
  description: "Project for my-app service"
  sourceRepos:
    - https://github.com/BBSSJJ/gitops-study
  destinations:
    - namespace: my-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'