apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-query-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: order-query=0326bsj/order-query-server
    argocd-image-updater.argoproj.io/order-query.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-user: BBSSJJ
    argocd-image-updater.argoproj.io/git-email: bdhbsj@naver.com
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/BBSSJJ/gitops-study
    targetRevision: HEAD
    path: order-query-server
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
