apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-root
  namespace: argocd
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/BBSSJJ/gitops-study
    targetRevision: HEAD
    path: applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
