apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/image-list: web=yourdockerid/web-server
    argocd-image-updater.argoproj.io/web.update-strategy: latest
    argocd-image-updater.argoproj.io/web.allow-tags: regexp:^.*$
    argocd-image-updater.argoproj.io/web.write-back-method: git:secret:argocd/image-updater-credentials
spec:
  project: my-app-project
  source:
    repoURL: https://github.com/BBSSJJ/gitops-study
    targetRevision: HEAD
    path: web-server
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
