apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-command-server-hpa
  namespace: my-app
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: order-command-server
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
        - type: Percent
          value: 50
          periodSeconds: 60

