apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: my-app
  labels:
    app: mongodb
spec:
  clusterIP: None  # StatefulSet용 헤드리스 서비스
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: my-app
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017