apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: my-app
  labels:
    app: mongodb
spec:
  serviceName: mongodb-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.29
          imagePullPolicy: IfNotPresent
          args: ["--bind_ip_all", "--noauth"]  # 무인증
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
