
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-query-server-scaler
  namespace: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-query-server
  minReplicaCount: 1         # 일이 없으면 완전 0
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: dev-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
        topic: new-order
        consumerGroup: order-group
        lagThreshold: "3"   # lag이 3개 초과 시 scale-up
        activationLagThreshold: "1"
