apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-kafka
  namespace: kafka
spec:
  kafka:
    # 오퍼레이터가 지원하는 Kafka 버전 사용 (예: 4.x/3.7+) 
    # 최신 릴리스 노트/문서에 맞추세요.
    listeners:
      - name: plain
        port: 9092
        type: internal    # 클러스터 내부용
        tls: false        # 학습/내부용이면 PLAINTEXT
    config:
      # 단일/소형 클러스터에 맞춘 최소 복제 파라미터
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      auto.create.topics.enable: true
  # 주의: KRaft 모드에서는 zookeeper 섹션이 없습니다.

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controllers
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  replicas: 1                 # 개발용 단일 컨트롤러(실운영은 3 권장)
  roles:
    - controller
  storage:
    type: ephemeral

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: brokers
  namespace: kafka
  labels:
    strimzi.io/cluster: dev-kafka
spec:
  replicas: 1                 # 개발용 1 브로커
  roles:
    - broker
  storage:
    type: ephemeral

